const WARNA_MERAH = "#F00"
const WARNA_BIRU = '#00F'
const WARNA_HIJAU = '#0F0'

//kETIKA INGIN MEMANGGIL WARNA KITA CUMA PERLU MENGGIL VARIABELNYA SAJA

let warnaBaju = WARNA_MERAH
console.log(warnaBaju);